-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgY4Vz1au7GdOlDmHy
NVA/BvUU9kkOI35meYsHOm+soNWgCgYIKoZIzj0DAQehRANCAARwFSe/TIzxFu3U
Rg4O5JRpPPsCqdZ+HG/ddyGre+RwvymbxpQa19ycH2bFOd7vaiDLf8QzQ7K0Kt+G
lTCNfR1U
-----END PRIVATE KEY-----